trigger:
- none

variables:
- name: EXP_NAME
  value: chaos-az-down
- name: SUB_NAME
  value: 43709a15-a023-45e7-90a6-e30c5ffad83e
- name: RG_NAME
  value: chaos

pool:
  vmImage: ubuntu-latest
stages:

- stage: terraform_stage
  displayName: Chaos Terraform stage
  jobs:
  - job: create_experiment
    displayName: Create chaos experiment with terraform
    steps:
    - task: TerraformInstaller@1
      displayName: terraform install
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/src'
        backendServiceArm: $(SUB_NAME)
        backendAzureRmResourceGroupName: $(RG_NAME)
        backendAzureRmStorageAccountName: 'terraform'
        backendAzureRmContainerName: 'state'
        backendAzureRmKey: 'file'

    - task: TerraformTaskV4@4
      displayName: terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/src/terraform'
        commandOptions: '-var-file=$(Build.SourcesDirectory)/src/terraform/envs/dev.tfvars'
        environmentServiceNameAzureRM: 'geralexgr-azure'




- stage: chaos_stage
  displayName: Chaos Experiment stage
  jobs:
  - job: run_experiment
    displayName: Run chaos experiment job
    steps:
    - task: AzureCLI@2
      displayName: run experiment to stop app service
      inputs:
        azureSubscription: 'MVP(43709a15-a023-45e7-90a6-e30c5ffad83e)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az rest --method post --uri https://management.azure.com/subscriptions/$(SUB_NAME)/resourceGroups/$(RG_NAME)/providers/Microsoft.Chaos/experiments/$(EXP_NAME)/start?api-version=2023-11-01'